# -*- coding: utf-8 -*-
"""阶段6扩库数据 —— 批次1: 人物主体 + 持有物(新建) + 场景环境。

条目格式:
  A  (en, zh)
  B  (en, zh, weight)
  C  (en, zh, nsfw)   nsfw=True 时打 🔞 标记
所有 en 必须是库中不存在的新标签 (应用脚本会强制查重)。
"""

BATCH1 = {
    # ---------------- 人物主体 ----------------
    "subject.s2.g1": {  # 发型 +10
        "adds": [
            ("low ponytail", "低马尾"),
            ("side braid", "侧编发"),
            ("fishtail braid", "鱼骨辫"),
            ("messy hair", "凌乱头发"),
            ("bedhead", "睡乱头发"),
            ("hair between eyes", "额发分帘"),
            ("swept-back hair", "背梳发型"),
            ("asymmetric hair", "不对称发型"),
            ("short twintails", "短双马尾"),
            ("updo", "盘发"),
        ],
    },
    "subject.haircolor": {  # 发色 +3
        "adds": [
            ("aqua hair", "水蓝色头发"),
            ("lavender hair", "薰衣草色头发"),
            ("platinum blonde hair", "白金色头发"),
        ],
    },
    "subject.s2.g2": {  # 眼部 +8
        "adds": [
            ("round eyes", "圆眼"),
            ("narrow eyes", "眯眼"),
            ("wide eyes", "瞪大双眼"),
            ("sparkling eyes", "星光亮眼"),
            ("flower-shaped pupils", "花形瞳孔"),
            ("cross-shaped pupils", "十字瞳孔"),
            ("both eyes open", "双眼睁开"),
            ("eyes visible through hair", "发间可见眼睛"),
        ],
    },
    "subject.s3": {  # 表情情绪 +46 (含微表情/嘴部动作, 后 9 个联动 legacy 冲突组)
        "adds": [
            ("happy", "开心"),
            ("laughing", "大笑"),
            ("cat mouth", "猫嘴"),
            ("giggle", "咯咯笑"),
            ("evil smile", "坏笑"),
            ("evil grin", "邪笑"),
            ("wide grin", "咧嘴笑"),
            ("cat smile", "猫式笑"),
            ("silly face", "鬼脸"),
            ("satisfied", "满足"),
            ("proud", "自豪"),
            ("serene", "安详"),
            ("nervous", "紧张"),
            ("anxious", "焦虑"),
            ("gritted teeth", "咬牙"),
            ("crazy smile", "疯狂笑容"),
            ("evil laugh", "邪恶大笑"),
            ("fake smile", "假笑"),
            ("wavy mouth", "波浪嘴"),
            ("deadpan", "面瘫脸"),
            ("sighing", "叹气"),
            ("sly smile", "狡黠一笑"),
            ("mischievous", "淘气"),
            ("seductive", "媚态"),
            ("bashful", "害臊"),
            ("arrogant", "傲慢"),
            ("triumphant", "得意"),
            ("furious", "狂怒"),
            ("grumpy", "臭脸"),
            ("sulking", "生闷气"),
            ("heartbroken", "心碎"),
            ("lonely", "孤单"),
            ("gloomy", "忧郁"),
            ("curious", "好奇"),
            ("dazed", "恍惚"),
            ("dizzy", "晕眩"),
            ("drunk", "醉态"),
            ("hypnotized", "被催眠"),
            ("sweating", "出汗"),
            ("nervous smile", "尴尬笑"),
            ("sleeping", "熟睡"),
            ("unconscious", "昏迷"),
            ("singing", "唱歌"),
            ("yelling", "大喊"),
            ("screaming", "尖叫"),
            ("eating", "吃东西"),
            ("drinking", "喝东西"),
        ],
    },
    "subject.extended": {  # 身体特征 +8 (非NSFW体质特征)
        "adds": [
            ("tattoo", "纹身"),
            ("scar", "伤疤"),
            ("bandages", "绷带"),
            ("pointy ears", "尖耳"),
            ("cat ears", "猫耳"),
            ("fox ears", "狐耳"),
            ("wolf ears", "狼耳"),
            ("horns", "角"),
        ],
    },
    # ---------------- 持有物 (新建子分类, 迁移用户库 imported.c1 的 32 个) ----------------
    "subject.props": {
        "name": "持有物",
        "new": True,
        "adopt": True,
        "adds": [
            # ← 迁移自用户库 imported.c1 (32)
            ("umbrella", "雨伞"), ("paper umbrella", "纸伞"),
            ("katana", "武士刀"), ("rapier", "细剑"),
            ("staff", "法杖"), ("magic wand", "魔杖"),
            ("spellbook", "魔法书"), ("book", "书"),
            ("teacup", "茶杯"), ("coffee cup", "咖啡杯"),
            ("ice cream", "冰淇淋"), ("lollipop", "棒棒糖"),
            ("pocky", "百奇"), ("apple", "苹果"),
            ("strawberry", "草莓"), ("bento", "便当"),
            ("smartphone", "手机"), ("game controller", "游戏手柄"),
            ("pen", "钢笔"), ("camera", "相机"),
            ("teddy bear", "泰迪熊"), ("plush toy", "毛绒玩具"),
            ("balloon", "气球"), ("bicycle", "自行车"),
            ("motorcycle", "摩托车"), ("skateboard", "滑板"),
            ("violin", "小提琴"), ("guitar", "吉他"),
            ("microphone", "麦克风"), ("basketball", "篮球"),
            ("tennis racket", "网球拍"), ("gun", "枪"),
            # 新扩武器 (13)
            ("sword", "剑"), ("scythe", "镰刀"),
            ("bow (weapon)", "弓"), ("shield", "盾牌"),
            ("spear", "长枪"), ("axe", "斧头"),
            ("dagger", "匕首"), ("kunai", "苦无"),
            ("shuriken", "手里剑"), ("sniper rifle", "狙击步枪"),
            ("pistol", "手枪"), ("lightsaber", "光剑"),
            ("chainsaw", "电锯"),
            # 新扩奇幻道具 (10)
            ("fan", "扇子"), ("folding fan", "折扇"),
            ("potion", "药水"), ("scroll", "卷轴"),
            ("crystal ball", "水晶球"), ("hourglass", "沙漏"),
            ("scepter", "权杖"), ("orb", "宝珠"),
            ("key", "钥匙"), ("lantern", "灯笼"),
            # 新扩食物饮品 (13)
            ("wine glass", "酒杯"), ("canned drink", "罐装饮料"),
            ("bubble tea", "珍珠奶茶"), ("ramen", "拉面"),
            ("cake", "蛋糕"), ("donut", "甜甜圈"),
            ("cookie", "饼干"), ("chocolate", "巧克力"),
            ("watermelon", "西瓜"), ("popsicle", "冰棍"),
            ("dango", "团子"), ("crepe", "可丽饼"),
            ("cotton candy", "棉花糖"),
            # 新扩日用品/数码 (12)
            ("playing cards", "扑克牌"), ("school bag", "书包"),
            ("backpack", "双肩包"), ("gift", "礼物盒"),
            ("notebook", "笔记本"), ("newspaper", "报纸"),
            ("open book", "摊开的书"), ("hand mirror", "手镜"),
            ("pillow", "枕头"), ("candle", "蜡烛"),
            ("sparkler", "手持仙女棒"), ("vr headset", "VR眼镜"),
            # 新扩生活/休闲 (12)
            ("bouquet", "花束"), ("rose", "玫瑰"),
            ("fishing rod", "鱼竿"), ("broom", "扫帚"),
            ("doll", "人偶"), ("cat", "猫"),
            ("dog", "狗"), ("rabbit", "兔子"),
            ("bird", "小鸟"), ("soccer ball", "足球"),
            ("baseball bat", "棒球棍"), ("dumbbell", "哑铃"),
        ],
    },
    # ---------------- 场景环境 ----------------
    "scene.s1": {  # 室内 +18
        "adds": [
            ("convenience store", "便利店"),
            ("supermarket", "超市"),
            ("shopping mall", "购物中心"),
            ("bookstore", "书店"),
            ("flower shop", "花店"),
            ("arcade (place)", "游戏厅"),
            ("karaoke", "卡拉OK"),
            ("movie theater", "电影院"),
            ("theater stage", "剧场舞台"),
            ("swimming pool", "游泳池"),
            ("hot spring", "温泉"),
            ("sauna", "桑拿房"),
            ("cockpit", "驾驶舱"),
            ("aquarium", "水族馆"),
            ("museum", "博物馆"),
            ("zoo", "动物园"),
            ("hallway", "走廊"),
            ("escalator", "扶梯"),
        ],
    },
    "scene.s2": {  # 室外 +27
        "adds": [
            ("balcony", "阳台"),
            ("tunnel", "隧道"),
            ("stairs", "楼梯"),
            ("construction site", "工地"),
            ("skyscraper", "摩天大楼"),
            ("windmill", "风车"),
            ("ferris wheel", "摩天轮"),
            ("roller coaster", "过山车"),
            ("carousel", "旋转木马"),
            ("circus", "马戏团"),
            ("tent", "帐篷"),
            ("campfire", "篝火"),
            ("festival", "祭典"),
            ("shrine", "神社"),
            ("torii", "鸟居"),
            ("pagoda", "宝塔"),
            ("garden", "花园"),
            ("japanese garden", "日式庭园"),
            ("greenhouse", "温室"),
            ("courtyard", "庭院"),
            ("wasteland", "荒地"),
            ("glacier", "冰川"),
            ("ice cave", "冰洞"),
            ("lava", "熔岩"),
            ("cliff", "悬崖"),
            ("island", "岛屿"),
            ("coral reef", "珊瑚礁"),
        ],
    },
    "scene.s3": {  # 幻想科幻 +14
        "adds": [
            ("airship", "飞艇"),
            ("hot air balloon", "热气球"),
            ("space", "太空"),
            ("planet", "行星"),
            ("nebula", "星云"),
            ("future city", "未来都市"),
            ("battlefield", "战场"),
            ("dungeon", "地牢"),
            ("prison", "监狱"),
            ("throne room", "王座厅"),
            ("alchemy lab", "炼金实验室"),
            ("pirate ship", "海盗船"),
            ("sailing ship", "帆船"),
            ("shipwreck", "沉船"),
        ],
    },
    "scene.timeweather": {  # 时间天气 +17 (补齐 season 四件套激活冲突组)
        "adds": [
            ("fireworks", "烟花"),
            ("hail", "冰雹"),
            ("tornado", "龙卷风"),
            ("eclipse", "日食"),
            ("meteor shower", "流星雨"),
            ("dawn", "晨光"),
            ("dusk", "黄昏"),
            ("afternoon", "午后"),
            ("evening", "傍晚"),
            ("spring (season)", "春天"),
            ("summer", "夏天"),
            ("autumn", "秋天"),
            ("winter", "冬天"),
            ("christmas", "圣诞节"),
            ("halloween", "万圣节"),
            ("new year", "新年"),
            ("valentine", "情人节"),
        ],
    },
    "scene.particles": {  # 氛围粒子 +7
        "adds": [
            ("light particles", "光粒子"),
            ("dust", "浮尘"),
            ("soap bubbles", "肥皂泡"),
            ("steam", "蒸汽"),
            ("confetti", "彩纸屑"),
            ("feathers", "飘落羽毛"),
            ("ash", "飞灰"),
        ],
    },
}
