# -*- coding: utf-8 -*-
"""阶段6扩库数据 —— 批次4: 材质特效 + 风格媒介 + 收尾整理。

整理项 (edits/dels/moves):
  - 风格媒介/二次元向: del "pixiv id reference" (元信息词, 不是风格),
    del "cell shading" (cel shading 错拼重复)
  - 风格媒介/艺术媒介: "sketch" 是媒介保留; 补齐绘画媒介
  - 材质/材质: 从 6 个扩到完整材质库
  - 服装细节 → 并入材质子分类的服装方向? 不动结构, 只扩
"""

BATCH4 = {
    # ---------------- 材质特效 ----------------
    "material.s1": {  # 材质 +26
        "adds": [
            ("silk", "丝绸"),
            ("satin", "缎面"),
            ("velvet", "天鹅绒"),
            ("wool", "羊毛"),
            ("denim", "牛仔布"),
            ("latex", "乳胶"),
            ("rubber", "橡胶"),
            ("pvc material", "PVC材质"),
            ("fur", "毛皮"),
            ("feather texture", "羽毛质感"),
            ("scale texture", "鳞片质感"),
            ("chitin", "甲壳质"),
            ("porcelain skin", "瓷肌"),
            ("marble texture", "大理石纹"),
            ("granite", "花岗岩"),
            ("obsidian", "黑曜石"),
            ("crystal", "水晶"),
            ("gold", "黄金"),
            ("silver material", "白银"),
            ("copper", "铜"),
            ("rust", "锈迹"),
            ("carbon fiber", "碳纤维"),
            ("chrome", "镀铬"),
            ("brass", "黄铜"),
            ("bamboo texture", "竹材"),
            ("wood grain", "木纹"),
        ],
    },
    "material.s2": {  # 视觉特效 +22
        "adds": [
            ("glow effects", "辉光特效"),
            ("luminous particles", "发光粒子"),
            ("falling glow", "飘落光点"),
            ("energy waves", "能量波"),
            ("magic effects", "魔法特效"),
            ("magic circle effect", "魔法阵特效"),
            ("rune glow", "符文发光"),
            ("ice crystal effects", "冰晶特效"),
            ("flame effects", "火焰特效"),
            ("fire aura", "火焰光环"),
            ("electric sparks", "电火花"),
            ("electric arcs", "电弧"),
            ("water droplets", "水珠"),
            ("rain drops on skin", "皮肤雨滴"),
            ("petals swirling", "花瓣旋舞"),
            ("glitch effects", "故障艺术特效"),
            ("datamosh", "数据损坏特效"),
            ("vhs artifacts", "VHS噪点"),
            ("scan lines", "扫描线"),
            ("double vision effect", "重影效果"),
            ("distortion effect", "扭曲特效"),
            ("soft glow filter", "柔光滤镜"),
        ],
        "dels": ["sparkle effects"],  # 与 sparkles 语义重复
    },
    "material.s3": {  # 服装细节 +14
        "adds": [
            ("ruffles", "荷叶边"),
            ("puff sleeves", "泡泡袖"),
            ("bishop sleeves", "主教袖"),
            ("detached sleeves", "分离袖"),
            ("draped sleeves", "垂袖"),
            ("high collar", "立领"),
            ("open collar", "敞领"),
            ("collar (clothing)", "衣领"),
            ("tassel", "流苏"),
            ("button details", "纽扣细节"),
            ("zipper details", "拉链细节"),
            ("buckle", "皮带扣"),
            ("studded", "铆钉装饰"),
            ("cross-laced clothes", "交叉系带"),
        ],
        "dels": ["transparent"],  # 移到材质做 "transparent clothes" 更明确
    },
    # ---------------- 风格媒介 ----------------
    "stylemed.s1": {  # 写实向 +7
        "adds": [
            ("photorealistic style", "照片级写实"),
            ("documentary photography", "纪实摄影"),
            ("portrait photography", "人像摄影"),
            ("film photography", "胶片摄影"),
            ("polaroid photo", "拍立得"),
            ("35mm photograph", "35mm胶片照"),
            ("cinematic still", "电影剧照"),
        ],
    },
    "stylemed.s2": {  # 二次元向 +18
        "adds": [
            ("90s anime style", "90年代动画风"),
            ("2000s anime style", "00年代动画风"),
            ("modern anime style", "现代动画风"),
            ("kyoto animation style", "京阿尼风"),
            ("ghibli style", "吉卜力风"),
            ("shoujo manga style", "少女漫画风"),
            ("shounen manga style", "少年漫画风"),
            ("seinen manga style", "青年漫画风"),
            ("moe style", "萌系画风"),
            ("kawaii art style", "可爱画风"),
            ("dark fantasy anime", "暗黑幻想动画风"),
            ("mecha anime style", "机甲动画风"),
            ("chibi style", "Q版画风"),
            ("oni mascot style", "和风妖怪画风"),
            ("ukiyo-e influence", "浮世绘影响"),
            ("doujinshi style", "同人志画风"),
            ("visual novel style", "视觉小说风"),
            ("galgame cg", "美少女游戏CG"),
        ],
        "dels": ["pixiv id reference", "cell shading"],
    },
    "stylemed.s3": {  # 艺术媒介 +14
        "adds": [
            ("pastel art", "色粉画"),
            ("charcoal drawing", "炭笔画"),
            ("colored pencil", "彩铅"),
            ("ballpoint pen sketch", "圆珠笔画"),
            ("stipple shading", "点彩"),
            ("woodblock print", "版画"),
            ("linocut", "麻胶版画"),
            ("stained glass", "彩绘玻璃"),
            ("mosaic", "马赛克拼贴"),
            ("collage", "拼贴画"),
            ("pixel art", "像素画"),
            ("vector art", "矢量插画"),
            ("low poly art", "低多边形"),
            ("concept art", "概念设计图"),
        ],
    },
    "stylemed.s4": {  # 题材风格 +14
        "adds": [
            ("art nouveau", "新艺术运动"),
            ("baroque", "巴洛克"),
            ("gothic style", "哥特风"),
            ("victorian era", "维多利亚风"),
            ("romanticism", "浪漫主义"),
            ("impressionist", "印象派"),
            ("surrealism", "超现实主义"),
            ("art deco", "装饰艺术"),
            ("brutalist", "粗野主义"),
            ("psychedelic art", "迷幻艺术"),
            ("vaporwave", "蒸汽波"),
            ("synthwave", "合成器浪潮"),
            ("dieselpunk", "柴油朋克"),
            ("solarpunk", "太阳朋克"),
        ],
    },
    "stylemed.colors": {  # 色彩调配 +14
        "adds": [
            ("warm colors", "暖色调"),
            ("cool colors", "冷色调"),
            ("monotone", "单色调"),
            ("complementary colors", "互补色"),
            ("analogous colors", "类似色"),
            ("triadic colors", "三色系"),
            ("limited palette", "有限色板"),
            ("duotone", "双色"),
            ("neon palette", "霓虹配色"),
            ("earth tones", "大地色系"),
            ("creamy colors", "奶油色系"),
            ("desaturated", "低饱和"),
            ("oversaturated", "高饱和"),
            ("iridescent palette", "幻彩配色"),
        ],
        "edits": {
            "contrast colors": {"zh": "对比色"},
            "dark palette": {"zh": "暗色调"},
        },
    },
}
