# -*- coding: utf-8 -*-
"""阶段6扩库数据 —— 批次2: 光影氛围(扩+清理) + 构图镜头 + 姿势动作。

edits: en → 要改的字段 (同步进默认库+用户库快照)
dels/moves: 默认库+用户库两侧同名标签一起处理
"""

BATCH2 = {
    # ---------------- 光影氛围 ----------------
    "lighting.s1": {  # 光源类型 +16
        "adds": [
            ("chiaroscuro", "明暗对照"),
            ("split lighting", "分割光"),
            ("loop lighting", "环形光"),
            ("butterfly lighting", "蝶形光"),
            ("rembrandt lighting", "伦勃朗光"),
            ("moonlight through window", "窗间月光"),
            ("torchlight", "火把光"),
            ("candle glow", "烛光晕"),
            ("moon glow", "月晕"),
            ("starlight", "星光"),
            ("ambient occlusion", "环境光遮蔽"),
            ("bounce lighting", "反射光"),
            ("practical lights", "实景光源"),
            ("underlighting", "底光"),
            ("overhead lighting", "顶光"),
            ("holographic display", "全息光源"),
        ],
    },
    "lighting.s2": {  # 特殊光线 +20
        "adds": [
            ("light filtering through leaves", "叶隙光"),
            ("sunbeam", "光柱"),
            ("rays of light", "射线光"),
            ("shafts of light", "光束"),
            ("sunset glow", "夕照"),
            ("morning light", "晨光"),
            ("afternoon light", "午后光线"),
            ("blue moonlight", "蓝月光"),
            ("silver moonlight", "银月光"),
            ("cold light", "冷光"),
            ("warm light", "暖光"),
            ("colorful lighting", "彩色光"),
            ("iridescent light", "虹彩光"),
            ("caustics", "焦散"),
            ("light refraction", "光折射"),
            ("glowing water", "发光水面"),
            ("laser lights", "激光"),
            ("strobe light", "频闪灯"),
            ("uv lighting", "紫外光"),
            ("flickering light", "闪烁光"),
        ],
        "dels": ["moonlight", "dappled moonlight"],  # 光源类型已有同名 (跨子分类去重)
        "edits": {
            "dispersion": {"zh": "色散", "desc": "光线色散效果 (光谱分离)"},
        },
    },
    "lighting.s3": {  # 氛围情绪 +14
        "adds": [
            ("romantic atmosphere", "浪漫氛围"),
            ("nostalgic atmosphere", "怀旧氛围"),
            ("tranquil", "宁静"),
            ("mysterious atmosphere", "神秘氛围"),
            ("tense atmosphere", "紧张氛围"),
            ("festive", "节日感"),
            ("lonely atmosphere", "孤寂氛围"),
            ("hopeful", "充满希望"),
            ("oppressive", "压抑"),
            ("ethereal", "空灵"),
            ("surreal mood", "超现实感"),
            ("intimate", "亲密感"),
            ("bittersweet", "苦乐参半"),
            ("somber", "昏暗低沉"),
        ],
        "edits": {
            "high contrast": {"zh": "高对比", "desc": "与 strong contrast 语义重复但皆为常用词, 保留"},
        },
    },
    # ---------------- 构图镜头 ----------------
    "camerawork.s1": {  # 取景范围 +8
        "adds": [
            ("medium shot", "中景"),
            ("medium close-up", "中特写"),
            ("wide angle shot", "广角取景"),
            ("silhouette shot", "剪影取景"),
            ("over-the-shoulder shot", "过肩取景"),
            ("selfie shot", "自拍取景"),
            ("insert shot", "插入镜头"),
            ("full-length portrait", "全身像"),
        ],
    },
    "camerawork.s2": {  # 视角 +7
        "adds": [
            ("high angle", "俯角"),
            ("low angle", "仰角"),
            ("dutch angle view", "斜角视角"),
            ("first-person view", "第一人称视角"),
            ("third-person view", "第三人称视角"),
            ("aerial view", "航拍视角"),
            ("drone shot", "无人机视角"),
        ],
    },
    "camerawork.s3": {  # 镜头语言 +9
        "adds": [
            ("tilt-shift", "移轴镜头"),
            ("anamorphic lens", "变形宽银幕镜头"),
            ("vintage lens", "复古镜头"),
            ("soft focus", "柔焦"),
            ("long exposure", "长曝光"),
            ("double exposure", "双重曝光"),
            ("motion blur", "动态模糊"),
            ("zoom blur", "变焦模糊"),
            ("rack focus", "移焦"),
        ],
    },
    "camerawork.composition": {  # 构图 +9
        "adds": [
            ("rule of thirds", "三分法"),
            ("golden ratio composition", "黄金比例构图"),
            ("radial composition", "放射构图"),
            ("spiral composition", "螺旋构图"),
            ("frame within a frame", "框中框构图"),
            ("off-center composition", "偏心构图"),
            ("low angle composition", "仰角构图"),
            ("fill the frame", "满幅构图"),
            ("juxtaposition", "并列对比构图"),
        ],
        "dels": ["rule of thirds composition"],  # 与新增 "rule of thirds" 同义, 保留标准叫法
    },
    # ---------------- 姿势动作 ----------------
    "pose.s1": {  # 姿势 +30
        "adds": [
            ("sitting on lap", "坐在腿上"),
            ("straddling", "跨坐"),
            ("side sit", "侧坐"),
            ("w-sitting", "W坐"),
            ("crossed ankles", "交叠脚踝"),
            ("one knee up", "单膝立起"),
            ("hugging pillow", "抱枕头"),
            ("hugging stuffed toy", "抱玩偶"),
            ("arms behind head", "枕手"),
            ("arm up", "单臂上举"),
            ("arm outstretched", "手臂前伸"),
            ("reaching towards viewer", "伸手向镜头"),
            ("hand up", "抬手"),
            ("hand to own mouth", "手掩口"),
            ("hand between legs", "手置腿间"),
            ("kneeling on one knee", "单膝跪地"),
            ("sitting on floor", "席地而坐"),
            ("lying on back", "仰卧"),
            (" curled up", "蜷缩"),
            ("crouch", "蹲伏"),
            ("v pose", "V字手势站姿"),
            ("contrapposto", "对立式平衡站姿"),
            ("leaning on wall", "倚墙"),
            ("leaning on table", "倚桌"),
            ("looking out window", "望向窗外"),
            ("mid-stride", "迈步中"),
            ("turning around", "转身回眸"),
            ("dodging", "闪避"),
            ("landing pose", "落地姿势"),
            ("hero pose", "英雄站姿"),
        ],
    },
    "pose.s3": {  # 手部动作 +18
        "adjust": {},
        "adds": [
            ("palm out", "掌心向外"),
            ("beckoning", "招手"),
            ("snap fingers", "打响指"),
            ("fist clench", "握拳"),
            ("fingers interlaced", "十指相扣"),
            ("pinching", "捏取"),
            ("hand on own chest", "手抚胸"),
            ("hands on own cheeks", "双手捧脸"),
            ("adjusting clothes", "整理衣服"),
            ("adjusting tie", "整理领带"),
            ("pulling collar", "拉衣领"),
            ("rolling up sleeves", "卷袖子"),
            ("buttoning", "扣纽扣"),
            ("tucking hair", "撩发"),
            ("wiping tears", "擦泪"),
            ("rubbing eyes", "揉眼睛"),
            ("scratching head", "挠头"),
            ("shaking hands", "握手"),
        ],
    },
    "pose.s4": {  # 视线 +8
        "adds": [
            ("looking into distance", "望远"),
            ("looking at own hands", "看着自己的手"),
            ("looking up at viewer", "仰视镜头"),
            ("looking down at viewer", "俯视镜头"),
            ("glancing sideways", "斜睨"),
            ("staring", "凝视"),
            ("eye contact", "对视"),
            ("half-lidded eyes gaze", "半阖眼凝视"),
        ],
    },
}
