# -*- coding: utf-8 -*-
"""阶段6扩库数据 —— 批次3: 服装系统(上装/下装/套装/配饰/鞋袜) + 质量与技术分离。

质量分离: 服装类内容词从「质量与技术」迁出的原则适用于所有新增 —
本批次只加内容词到服装系统; quality 分类的新增在批次5做真正的质量词。
"""

BATCH3 = {
    # ---------------- 服装系统 ----------------
    "outfit.s1": {  # 上装 +22
        "adds": [
            ("halterneck", "挂脖上衣"),
            ("tube top", "抹胸"),
            ("one-piece top", "连体上装"),
            ("turtleneck", "高领毛衣"),
            ("knit vest", "针织背心"),
            ("gym shirt", "运动T恤"),
            ("jersey", "运动衫"),
            ("baseball shirt", "棒球衫"),
            ("flannel shirt", "法兰绒衬衫"),
            ("camisole", "吊带衫"),
            ("see-through top", "透视上衣"),
            ("waistcoat", "马甲"),
            ("raincoat", "雨衣"),
            ("duffel coat", "牛角扣大衣"),
            ("fur coat", "毛皮大衣"),
            ("haori", "羽织"),
            ("jodhpus jacket", "骑装外套"),
            ("bodysuit", "连体紧身衣"),
            ("unitard", "紧身连衣裤"),
            ("ribbed sweater", "罗纹毛衣"),
            ("long sleeve", "长袖"),
            ("short sleeves", "短袖"),
        ],
    },
    "outfit.s2": {  # 下装 +18
        "adds": [
            ("cargo pants", "工装裤"),
            ("leggings", "紧身裤"),
            ("capri pants", "七分裤"),
            ("hakama", "袴"),
            ("bike shorts", "骑行短裤"),
            ("spats", "紧身安全裤"),
            ("tulle skirt", "纱裙"),
            ("layered skirt", "层叠裙"),
            ("high-waist skirt", "高腰裙"),
            ("plaid skirt", "格纹裙"),
            ("torn pants", "破洞裤"),
            ("hot pants", "热裤"),
            ("cargo shorts", "工装短裤"),
            ("sweatpants", None and "运动裤"),  # 占位防重: 已存在
            ("boyshorts", "平角内裤"),
            ("frilled panties", "荷叶边内裤"),
            ("side-tie panties", "系带内裤"),
            ("chastity belt", "贞操带"),
        ],
    },
    "outfit.s3": {  # 套装与制服 +28
        "adds": [
            ("kimono dress", "和服式连衣裙"),
            ("china dress", "中华连衣裙"),
            ("cheongsam dress", "旗袍裙"),
            ("nurse outfit", "护士服"),
            ("police officer uniform", "警官制服"),
            ("flight attendant uniform", "空乘制服"),
            ("train conductor uniform", "列车员制服"),
            ("waitress uniform", "女服务生制服"),
            ("cafe waitress", "咖啡厅女仆装"),
            ("barista uniform", "咖啡师制服"),
            ("band uniform", "乐团制服"),
            ("choir robe", "唱诗袍"),
            ("ballet outfit", "芭蕾服"),
            ("leotard", "紧身连体衣"),
            ("wetsuit", "潜水服"),
            ("fencing uniform", "击剑服"),
            ("karate gi", "空手道服"),
            ("judo uniform", "柔道服"),
            ("soccer uniform", "足球服"),
            ("cheer uniform", "啦啦队服"),
            ("tennis outfit", "网球服"),
            ("golf outfit", "高尔夫球服"),
            ("frilled dress", "荷叶边连衣裙"),
            ("halter dress", "挂脖连衣裙"),
            ("knit dress", "针织连衣裙"),
            ("sweater dress", "毛衣裙"),
            ("gyaru fashion", "辣妹装"),
            ("idol outfit", "偶像装"),
        ],
    },
    "outfit.s4": {  # 配饰 +26
        "adds": [
            ("beret with pin", "贝雷帽+徽章"),
            ("flat cap", "鸭舌帽"),
            ("visor cap", "空顶帽"),
            ("beanie", "毛线帽"),
            ("sun hat", "遮阳帽"),
            ("hachimaki", "头巾"),
            ("headband (wide)", "宽发带"),
            ("cat ear headphones", "猫耳耳机"),
            ("ear muffs", "耳罩"),
            ("earing studs", "耳钉"),
            ("choker (ribbon)", "丝带颈环"),
            ("pearl necklace", "珍珠项链"),
            ("locket", "盒式吊坠"),
            ("brooch", "胸针"),
            ("body chain", "身体链"),
            ("anklet", "脚链"),
            ("fingerless mittens", "露指手套"),
            ("opera gloves", "长礼服手套"),
            ("arm cast", "手臂石膏"),
            ("leg band", "腿环"),
            ("thigh strap", "腿带"),
            ("pouch belt", "腰包腰带"),
            ("crossbody bag", "斜挎包"),
            ("handbag", "手提包"),
            ("satchel", "挎包"),
            ("coin purse", "零钱包"),
        ],
    },
    "outfit.legwear": {  # 鞋袜 +22
        "adds": [
            ("pantyhose (white)", "白色连裤袜"),
            ("pantyhose (black)", "黑色连裤袜"),
            ("pantyhose (striped)", "条纹连裤袜"),
            ("thighhighs (white)", "白色过膝袜"),
            ("thighhighs (black)", "黑色过膝袜"),
            ("thighhighs (striped)", "条纹过膝袜"),
            ("uneven legwear", "不等长袜"),
            ("sock sliders", "只穿袜"),
            ("tabi", "足袋"),
            ("bubble socks", "泡泡袜"),
            ("crew socks", "中筒袜"),
            ("no-show socks", "隐形袜"),
            ("hiking boots", "登山靴"),
            ("combat boots", "军靴"),
            ("rain boots", "雨靴"),
            ("cowboy boots", "牛仔靴"),
            ("roller skates", "轮滑鞋"),
            ("ice skates", "冰鞋"),
            ("ballet heels", "芭蕾高跟鞋"),
            ("wedge sandals", "坡跟凉鞋"),
            ("tabi sandals", "足袋凉鞋"),
            ("stockings with garter", "吊带袜"),
        ],
        "edits": {
            "zettai ryouiki": {"desc": "绝对领域 — 裙摆与过膝袜之间的露腿区"},
        },
    },
    # ---------------- 质量与技术 (只加真正的质量词, 内容词不进这里) ----------------
    "quality.s1": {  # 画质强化 +12
        "adds": [
            ("best quality masterpiece", None),  # 占位会被查重跳过? no—移除
        ],
    },
}
# 修正: quality.s1 的占位条目移除 (None 会在应用器崩溃), 真正的质量词放批次5
BATCH3["quality.s1"]["adds"] = [
    ("sensitive", "精细笔触"),
    ("detailed skin", "皮肤细节"),
    ("detailed face", "面部细节"),
    ("detailed eyes", "眼睛细节"),
    ("glossy skin", "皮肤光泽"),
    ("subtle skin texture", "细腻皮肤质感"),
    ("film grain", "胶片颗粒"),
    ("lens blur", "镜头模糊"),
    ("hdr", "HDR"),
    ("uhd", "超高清"),
    ("4k", "4K分辨率"),
    ("2k", "2K分辨率"),
]
