# -*- coding: utf-8 -*-
"""扩展包策展词表 (v1.8.0) —— NSFW 词表体系 + SFW 高频词补齐。

条目格式: (danbooru 名(下划线), 中文, 可选 kwargs)
  g="female"/"male"   性别标记 (影响性别三态池)
  h=N                 双手资源占用 (paizuri=2, handjob=1 …)
  nsfw=False          该词不作 NSFW 处理 (默认 True)
  min=N               收录门槛 (post_count >= N, 默认 MIN_COUNT)

所有词都会经 danbooru post_count 校验: 无数据或低于门槛 → 丢弃并在报告列明。
与现有库 en 重名的词自动跳过 (不重复收录)。
"""

# 默认收录门槛: danbooru post_count。低于此值 = 模型见得太少, 收了也拉低质量。
MIN_COUNT = 1500

# ---------------------------------------------------------------- 新槽位词表

# 服装/服装状态 —— 半脱机制: 穿着完整度与部位状态 (与完整服装的互斥走 nsfw_conflicts)
CLOTH_STATE = [
    ("clothes_lift", "掀起衣物"),
    ("clothes_pull", "拉扯衣物"),
    ("shirt_lift", "掀起上衣"),
    ("skirt_lift", "掀起裙子"),
    ("lifting_own_clothes", "自己掀起衣物"),
    ("clothing_aside", "拨开衣物"),
    ("clothes_aside", "拨开衣物"),
    ("panty_pull", "拉开内裤"),
    ("panties_aside", "内裤拨到一边"),
    ("panties_around_one_leg", "内裤挂单腿"),
    ("top-down_bottom-up", "上撩下拉"),
    ("open_clothes", "敞开衣物", {"nsfw": False}),
    ("open_shirt", "敞开衬衫", {"nsfw": False}),
    ("open_jacket", "敞开外套", {"nsfw": False}),
    ("no_panties", "没穿内裤"),
    ("no_pants", "没穿裤子"),
    ("no_bra", "没穿胸罩"),
    ("no_shoes", "没穿鞋", {"nsfw": False}),
    ("underwear_only", "只穿内衣"),
    ("bikini_top_only", "只穿比基尼上装"),
    ("naked_shirt", "只穿衬衫"),
    ("naked_apron", "裸体围裙"),
    ("naked_towel", "裸体浴巾"),
    ("naked_ribbon", "裸体丝带"),
    ("see-through_clothes", "透视衣物"),
    ("see-through_sweater", "透视毛衣"),
    ("torn_clothes", "破损衣物", {"nsfw": False}),
    ("torn_pantyhose", "破洞连裤袜"),
    ("wet_clothes", "湿身衣物"),
    ("wet_shirt", "湿透衬衫"),
    ("clothing_cutout", "镂空衣物"),
    ("cupless_bra", "无罩杯胸罩"),
    ("crotchless_panties", "开裆内裤"),
    ("pull_over_waist", "褪到腰间"),
    ("pull_over_breasts", "褪到乳下"),
    ("unbuttoned", "解开纽扣", {"nsfw": False}),
    ("unworn_jacket", "披而不穿", {"nsfw": False}),
    ("underwear_pulled_down", "内裤褪下"),
    ("underwear_pull", "拉下内裤"),
    ("breasts_apart_through_clothes", "衣物分开双乳"),
    ("ass_visible_through_thighs", "腿缝见臀"),
    ("pubic_hair_peek", "阴毛微露"),
    ("areolae_peek", "乳晕微露"),
    ("underboob_cutoff", "下乳截断"),
    ("side-tie_bikini_bottom", "侧系比基尼下装"),
    ("side-tie_panties", "侧系内裤"),
    ("bow_panties", "蝴蝶结内裤"),
    ("highleg_panties", "高衩内裤"),
    ("highleg_leotard", "高衩紧身衣"),
    ("panties_under_pantyhose", "裤袜内穿内裤"),
    ("pre_clothes_pull", "将脱未脱"),
    ("between_breasts", "乳间夹物"),
]

# 外貌特征/身体细节 —— 解剖细节与私密部位描写 (高频词, 模型理解度极高)
BODY_DETAIL = [
    ("pussy", "阴部", {"g": "female"}),
    ("penis", "阴茎", {"g": "male"}),
    ("anus", "后穴"),
    ("testicles", "睾丸", {"g": "male"}),
    ("clitoris", "阴蒂", {"g": "female"}),
    ("clitoral_hood", "阴蒂包皮下", {"g": "female"}),
    ("cleft_of_venus", "维纳斯之丘", {"g": "female"}),
    ("perineum", "会阴"),
    ("groin", "腹股沟"),
    ("uterus", "子宫", {"g": "female"}),
    ("foreskin", "包皮", {"g": "male"}),
    ("large_penis", "巨根", {"g": "male"}),
    ("huge_penis", "超大阴茎", {"g": "male"}),
    ("veiny_penis", "青筋阴茎", {"g": "male"}),
    ("erection", "勃起", {"g": "male"}),
    ("precum", "前液", {"g": "male"}),
    ("puffy_nipples", "蓬松乳头", {"g": "female"}),
    ("large_areolae", "大乳晕", {"g": "female"}),
    ("inverted_nipples", "凹陷乳头", {"g": "female"}),
    ("puffy_areolae", "蓬松乳晕", {"g": "female"}),
    ("nipple_piercing", "乳钉", {"g": "female"}),
    ("female_pubic_hair", "女性阴毛", {"g": "female"}),
    ("male_pubic_hair", "男性阴毛", {"g": "male"}),
    ("colored_pubic_hair", "异色阴毛"),
    ("unshaved_pubic_hair", "未剃阴毛"),
    ("skindentation", "皮肤压痕", {"nsfw": False}),
    ("shiny_skin", "光泽肌肤", {"nsfw": False}),
    ("curves", "曲线", {"g": "female", "nsfw": False}),
    ("bare_legs", "裸腿", {"g": "female", "nsfw": False}),
    ("armpits", "腋下", {"nsfw": False}),
    ("armpit_hair", "腋毛", {"nsfw": False}),
    ("navel", "肚脐", {"nsfw": False}),
    ("covered_navel", "遮住肚脐", {"nsfw": False}),
    ("collarbone", "锁骨", {"nsfw": False}),
    ("feet", "双足", {"nsfw": False}),
    ("soles", "脚底", {"nsfw": False}),
    ("toes", "脚趾", {"nsfw": False}),
    ("thighs", "大腿", {"g": "female", "nsfw": False}),
]

# 动作姿态/体位 —— 体位 (互斥域 nsfw.sex_position; 与站/坐/躺互斥走 posture_base)
POSITIONS = [
    ("missionary", "正常位"),
    ("doggystyle", "后入位"),
    ("cowgirl_position", "骑乘位"),
    ("reverse_cowgirl_position", "后侧骑乘位"),
    ("squatting_cowgirl_position", "蹲踞骑乘位"),
    ("prone_bone", "俯卧位"),
    ("upright_straddle", "立位跨坐"),
    ("sex_from_behind", "背后位"),
    ("standing_sex", "站立位"),
    ("girl_on_top", "女上位"),
    ("boy_on_top", "男上位"),
    ("folded", "折叠体位"),
    ("m_legs", "M 形开腿"),
    ("legs_up", "抬腿"),
    ("legs_towards_head", "腿举过头"),
    ("w_shape", "W 坐开腿"),
    ("spread_legs", "张开双腿"),
    ("straddling", "跨坐"),
    ("sitting_on_person", "坐于人身上"),
    ("straddling_paizuri", "跨坐乳交", {"h": 2}),
    ("squatting", "蹲姿", {"nsfw": False}),
    ("all_fours", "四肢着地", {"nsfw": False}),
    ("bent_over", "弯腰撅臀", {"nsfw": False}),
    ("head_back", "头后仰"),
    ("lying", "躺卧", {"nsfw": False}),
    ("on_back", "仰卧", {"nsfw": False}),
    ("on_side", "侧卧", {"nsfw": False}),
    ("on_stomach", "俯卧", {"nsfw": False}),
]

# 动作姿态/性行为 —— 行为动词 (口部词走 legacy.mouth 域; 阴道/后庭走 nsfw.penetration)
SEX_ACTS = [
    ("sex", "性行为"),
    ("hetero", "异性性行为"),
    ("yuri", "百合"),
    ("yaoi", "男男"),
    ("vaginal", "阴道性交"),
    ("anal", "肛交"),
    ("anal_object_insertion", "肛部异物"),
    ("vaginal_object_insertion", "阴道异物"),
    ("double_penetration", "双重插入"),
    ("oral", "口交(总称)"),
    ("fellatio", "口交"),
    ("irrumatio", "深插口交"),
    ("deepthroat", "深喉"),
    ("cooperative_fellatio", "双人协同口交"),
    ("cunnilingus", "舔阴"),
    ("licking_penis", "舔舐阴茎"),
    ("licking_pussy", "舔舐阴部"),
    ("paizuri", "乳交", {"h": 2}),
    ("paizuri_under_clothes", "衣内乳交", {"h": 2}),
    ("handjob", "手交", {"h": 1}),
    ("footjob", "足交", {"h": 0}),
    ("two-footed_footjob", "双足交", {"h": 0}),
    ("footjob_with_legwear", "着袜足交"),
    ("fingering", "指交", {"h": 1}),
    ("clitoral_stimulation", "刺激阴蒂", {"h": 1}),
    ("nipple_stimulation", "刺激乳头", {"h": 1}),
    ("breast_sucking", "吸吮乳房"),
    ("licking_breasts", "舔舐乳房"),
    ("nipple_tweak", "拧弄乳头", {"h": 1}),
    ("breast_press", "胸部挤压"),
    ("bouncing_breasts", "晃动双乳"),
    ("breasts_squeezed_together", "挤拢双乳", {"h": 2}),
    ("grabbing_another's_breast", "抓握他人乳房", {"h": 1}),
    ("grabbing_own_breast", "抓握自己乳房", {"h": 1}),
    ("groping", "袭胸", {"h": 1}),
    ("grabbing_another's_ass", "抓握他人臀部", {"h": 1}),
    ("grabbing_from_behind", "背后搂抱", {"h": 1}),
    ("masturbation", "自慰", {"h": 1}),
    ("female_masturbation", "女性自慰", {"h": 1, "g": "female"}),
    ("male_masturbation", "男性自慰", {"h": 1, "g": "male"}),
    ("futanari_masturbation", "扶她自慰", {"h": 1}),
    ("mutual_masturbation", "互相自慰", {"h": 1}),
    ("crotch_rub", "磨蹭裆部", {"h": 1}),
    ("crotch_rub_through_clothes", "隔衣磨蹭", {"h": 1}),
    ("masturbation_through_clothes", "隔衣自慰", {"h": 1}),
    ("grinding", "磨蹭"),
    ("intercrural", "腿交"),
    ("kiss", "亲吻"),
    ("kissing", "接吻中"),
    ("kissing_neck", "吻颈"),
    ("licking", "舔舐", {"nsfw": False}),
    ("licking_lips", "舔唇"),
    ("licking_another's_fingers", "舔舐他人手指"),
    ("spitroast", "前后夹击"),
    ("threesome", "三人行"),
    ("ffm_threesome", "女女男三人行"),
    ("mmf_threesome", "男女男三人行"),
    ("foursome", "四人行"),
    ("group_sex", "群交"),
    ("gangbang", "轮番侵犯"),
    ("orgy", "狂欢群交"),
    ("surrounded_by_penises", "环体围男", {"g": "female"}),
    ("teamwork_(sexual)", "协同性行为"),
    ("interracial", "异族配"),
    ("bisexual_female", "双性恋女", {"g": "female"}),
    ("femdom", "女性支配"),
    ("maledom", "男性支配", {"min": 1000}),
    ("assertive_female", "强势女性", {"g": "female"}),
    ("age_difference", "年龄差"),
    ("size_difference", "体型差"),
    ("clothed_sex", "着衣性交"),
    ("after_sex", "事后"),
    ("after_vaginal", "阴道事后"),
    ("happy_sex", "欢愉性交"),
    ("fucked_silly", "神志失守"),
    ("condom", "安全套"),
    ("condom_on_penis", "戴套"),
]

# 动作姿态/束缚与调教 —— 捆绑/拘束/调教动作
BONDAGE_ACTS = [
    ("bdsm", "BDSM"),
    ("bondage", "捆绑"),
    ("bound", "被捆绑"),
    ("restrained", "被拘束"),
    ("bound_wrists", "手腕被缚"),
    ("bound_arms", "手臂被缚"),
    ("bound_legs", "双腿被缚"),
    ("bound_ankles", "脚踝被缚"),
    ("shibari", "绳缚"),
    ("red_rope", "红绳缚"),
    ("breast_bondage", "乳房束缚"),
    ("crotch_rope", "裆绳"),
    ("suspension", "吊缚"),
    ("frogtie", "蛙式缚"),
    ("arm_held_back", "反剪手臂"),
    ("gagged", "被塞口"),
    ("ball_gag", "口球"),
    ("cloth_gag", "布团塞口"),
    ("tape_gag", "胶带封口"),
    ("improvised_gag", "就地取材塞口"),
    ("wiffle_gag", "网眼口球"),
    ("blindfold", "眼罩", {"nsfw": False}),
    ("collar", "项圈"),
    ("leash", "牵绳"),
    ("holding_leash", "手执牵绳", {"h": 1}),
    ("slave", "奴隶"),
    ("pet_play", "宠物扮演"),
    ("forced_orgasm", "被迫高潮"),
    ("teasing", "挑逗"),
]

# 动作姿态/高潮与体液 —— 高潮/射精/体液 (目标域 nsfw.cum_target 单选)
CLIMAX = [
    ("orgasm", "高潮"),
    ("female_orgasm", "女性高潮", {"g": "female"}),
    ("ejaculation", "射精", {"g": "male"}),
    ("female_ejaculation", "女性潮吹", {"g": "female"}),
    ("ejaculating_while_penetrated", "插入中射精", {"g": "male"}),
    ("cum", "精液", {"g": "male"}),
    ("cumdrip", "精液滴落", {"g": "male"}),
    ("cum_overflow", "精液溢出", {"g": "male"}),
    ("cum_in_pussy", "体内射精", {"g": "male"}),
    ("internal_cumshot", "深部射精", {"g": "male"}),
    ("cum_in_mouth", "口中射精", {"g": "male"}),
    ("cum_in_ass", "后穴射精", {"g": "male"}),
    ("cum_on_body", "身躯射精", {"g": "male"}),
    ("cum_on_breasts", "胸前射精", {"g": "male"}),
    ("cum_on_hair", "发间射精", {"g": "male"}),
    ("cum_on_feet", "足上射精", {"g": "male"}),
    ("cum_on_clothes", "衣物射精", {"g": "male"}),
    ("cum_on_face", "颜射", {"g": "male"}),
    ("facial", "颜射(总称)", {"g": "male"}),
    ("bukkake", "颜射群交", {"g": "male"}),
    ("projectile_cum", "喷射精液", {"g": "male"}),
    ("pussy_juice", "爱液", {"g": "female"}),
    ("pussy_juice_drip", "爱液滴落", {"g": "female"}),
    ("saliva", "唾液"),
    ("drooling", "流涎", {"nsfw": False}),
    ("saliva_trail", "唾液拉丝"),
    ("trembling", "颤抖", {"nsfw": False}),
    ("spasms", "痉挛"),
    ("shiver", "颤栗", {"nsfw": False}),
    ("afterglow", "事后余韵"),
    ("post-orgasm", "高潮之后"),
    ("flushed_skin", "潮红肌肤"),
    ("sweat", "汗水", {"nsfw": False}),
    ("sweatdrop", "汗滴", {"nsfw": False}),
    ("heavy_breathing", "急促呼吸"),
    ("moaning", "呻吟"),
    ("speechless", "失语"),
    ("ahegao", "阿黑颜"),
]

# 道具武器/束缚道具 —— 拘束具与成人玩具
BDSM_PROPS = [
    ("sex_toy", "成人玩具"),
    ("holding_sex_toy", "手持成人玩具", {"h": 1}),
    ("dildo", "假阳具"),
    ("vibrator", "震动棒"),
    ("vibrator_under_clothes", "衣内震动棒"),
    ("remote_control_vibrator", "遥控震动棒"),
    ("egg_vibrator", "跳蛋"),
    ("hitachi_magic_wand", "魔法棒"),
    ("anal_beads", "肛珠"),
    ("butt_plug", "肛塞"),
    ("anal_tail", "肛塞尾巴"),
    ("onahole", "自慰套"),
    ("strap-on", "穿戴式假阳具"),
    ("double-sided_dildo", "双头假阳具"),
    ("rope", "绳索", {"nsfw": False}),
    ("red_rope", "红绳", {"nsfw": False}),
    ("cuffs", "手铐", {"nsfw": False}),
    ("handcuffs", "手铐(双手)", {"nsfw": False}),
    ("tape", "胶带", {"nsfw": False}),
    ("chain", "锁链", {"nsfw": False}),
    ("spreader_bar", "张腿杆"),
]

# 角色身份/种族与幻想身份 追加
CHARACTER_ADD = [
    ("futanari", "扶她"),
]

# 外貌特征/表情 追加
EXPRESSION_ADD = [
    ("rolling_eyes", "翻白眼"),
    ("torogao", "沉迷表情"),
    ("moaning", "呻吟"),
    ("unusual_pupils", "异形瞳孔", {"nsfw": False}),
    ("crying_with_eyes_open", "睁眼流泪", {"nsfw": False}),
]

# 外貌特征/眼部 追加
EYES_ADD = [
    ("heart-shaped_pupils", "心形瞳孔"),
    ("symbol-shaped_pupils", "符号瞳孔", {"nsfw": False}),
    ("half-closed_eyes", "半闭眼", {"nsfw": False}),
]

# 外貌特征/情绪与状态 追加
MOOD_ADD = [
    ("aroused", "情动"),
    ("embarrassed", "害羞", {"nsfw": False}),
    ("pouting", "嘟嘴", {"nsfw": False}),
]

# 外貌特征/体型 追加
BODY_SHAPE_ADD = [
    ("ass", "臀部"),
    ("huge_ass", "巨臀"),
    ("thick_thighs", "粗腿", {"g": "female", "nsfw": False}),
    ("abs", "腹肌", {"nsfw": False}),
    ("pectoralis", "胸肌", {"g": "male", "nsfw": False}),
    ("large_pectorals", "发达胸肌", {"g": "male", "nsfw": False}),
    ("muscular_male", "肌肉男", {"g": "male", "nsfw": False}),
    ("curvy", "丰腴", {"g": "female", "nsfw": False}),
    ("hips", "胯部", {"nsfw": False}),
    ("wide_hips", "宽胯", {"g": "female", "nsfw": False}),
    ("plump", "丰润", {"nsfw": False}),
    ("flat_chest", "平胸", {"g": "female"}),
    ("hanging_breasts", "下垂乳房", {"g": "female"}),
]

# 道具武器/日用道具 追加 (成人玩具归日用道具)
TOYS_ADD = [
    ("sex_toy", "成人玩具"),
    ("dildo", "假阳具"),
    ("vibrator", "震动棒"),
    ("egg_vibrator", "跳蛋"),
    ("anal_beads", "肛珠"),
    ("butt_plug", "肛塞"),
    ("onahole", "自慰套"),
    ("strap-on", "穿戴式假阳具"),
]

# 场景环境/室内 追加
INDOOR_ADD = [
    ("bed", "床", {"nsfw": False}),
    ("bed_sheet", "床单", {"nsfw": False}),
    ("sofa", "沙发", {"nsfw": False}),
    ("bath", "浴池", {"nsfw": False}),
    ("hot_spring", "温泉", {"nsfw": False}),
    ("shower", "淋浴", {"nsfw": False}),
    ("steam", "蒸汽", {"nsfw": False}),
    ("locker_room", "更衣室", {"nsfw": False}),
    ("love_hotel", "情人旅馆"),
]


# ---------------------------------------------------------------- SFW 高频补齐
# (danbooru 名, 目标槽位 "轴/槽位") —— 全部 nsfw=False, 仅当库内缺该词且 post_count 达标才收录
TOPUP = [
    # --- 基础词空洞 (实测缺失的高频词: 蓝发1.2M/内裤820k/比基尼702k...) ---
    ("blue_hair", "外貌特征/发色", "蓝发"),
    ("long_sleeves", "服装/服装细节", "长袖"),
    ("collared_shirt", "服装/上装", "带领衬衫"),
    ("black_jacket", "服装/上装", "黑色外套"),
    ("vest", "服装/上装", "背心"),
    ("black_pants", "服装/下装", "黑色长裤"),
    ("short_shorts", "服装/下装", "热裤"),
    ("black_skirt", "服装/下装", "黑色短裙"),
    ("panties", "服装/腿袜与内衣", "内裤"),
    ("white_panties", "服装/腿袜与内衣", "白色内裤"),
    ("black_panties", "服装/腿袜与内衣", "黑色内裤"),
    ("pink_panties", "服装/腿袜与内衣", "粉色内裤"),
    ("blue_panties", "服装/腿袜与内衣", "蓝色内裤"),
    ("striped_panties", "服装/腿袜与内衣", "条纹内裤"),
    ("black_bra", "服装/腿袜与内衣", "黑色胸罩"),
    ("white_bra", "服装/腿袜与内衣", "白色胸罩"),
    ("toeless_legwear", "服装/腿袜与内衣", "露趾裤袜"),
    ("bikini", "服装/特色与运动装", "比基尼"),
    ("black_bikini", "服装/特色与运动装", "黑色比基尼"),
    ("white_bikini", "服装/特色与运动装", "白色比基尼"),
    ("one-piece_swimsuit", "服装/特色与运动装", "连体泳衣"),
    ("school_swimsuit", "服装/特色与运动装", "学校泳衣"),
    ("highleg", "服装/特色与运动装", "高衩"),
    ("japanese_clothes", "服装/传统与民族", "日本服饰"),
    ("alternate_costume", "服装/服装细节", "私服换装"),
    ("official_alternate_costume", "服装/服装细节", "官方换装"),
    ("fur_trim", "服装/服装细节", "毛皮镶边"),
    ("facial_hair", "外貌特征/妆容与胡须", "胡须"),
    ("colored_skin", "外貌特征/皮肤与印记", "异色皮肤"),
    ("dark-skinned_female", "外貌特征/皮肤与印记", "深肤色女性", {"g": "female"}),
    ("dark-skinned_male", "外貌特征/皮肤与印记", "深肤色男性", {"g": "male"}),
    ("deep_skin", "外貌特征/皮肤与印记", "深色肌肤"),
    ("veins", "外貌特征/皮肤与印记", "青筋"),
    ("fingernails", "外貌特征/皮肤与印记", "指甲"),
    ("toenails", "外貌特征/皮肤与印记", "脚趾甲"),
    ("toenail_polish", "外貌特征/皮肤与印记", "脚趾甲油"),
    ("animal_ear_fluff", "外貌特征/非人特征", "兽耳绒毛"),
    ("fake_animal_ears", "外貌特征/非人特征", "假兽耳"),
    ("fake_tail", "外貌特征/非人特征", "假尾巴"),
    ("furry", "角色身份/种族与幻想身份", "兽人"),
    ("holding", "动作姿态/手部动作", "手持物品"),
    ("hands_up", "动作姿态/手部动作", "双手举起"),
    ("hand_on_another's_head", "动作姿态/互动与双人", "手放他人头上"),
    ("grabbing_another's_arm", "动作姿态/互动与双人", "抓住他人手臂"),
    ("torso_grab", "动作姿态/互动与双人", "抓住躯干"),
    ("day", "场景环境/时间时段", "白天"),
    ("grey_background", "场景环境/背景处理", "灰色背景"),
    ("pink_background", "场景环境/背景处理", "粉色背景"),
    ("dakimakura_(medium)", "道具武器/日用道具", "等身抱枕"),
    ("virtual_youtuber", "风格媒介/题材风格", "VTuber"),
    ("male_focus", "构图镜头/构图", "男性主体"),
    ("pov_hands", "构图镜头/视角", "第一人称手部"),
    ("female_pov", "构图镜头/视角", "女性视角"),
    ("pov_crotch", "构图镜头/视角", "裆部视角"),
    ("foot_focus", "构图镜头/构图", "足部特写"),
    ("ass_focus", "构图镜头/构图", "臀部特写"),
    ("pantyshot", "构图镜头/视角", "内裤镜头"),
    ("4boys", "人数/人数", "四男孩", {"g": "male"}),
    ("5boys", "人数/人数", "五男孩", {"g": "male"}),
    ("6+boys", "人数/人数", "六男孩及以上", {"g": "male"}),
    # --- 动作/视线/构图 泛用补齐 ---
    ("looking_back", "动作姿态/视线", "回眸"),
    ("looking_at_another", "动作姿态/视线", "看向他人"),
    ("looking_afar", "动作姿态/视线", "眺望远方"),
    ("one_eye_closed", "外貌特征/眼部", "单眼闭合"),
    ("heart_hands", "动作姿态/手部动作", "比心手势"),
    ("outstretched_arms", "动作姿态/手部动作", "张开双臂"),
    ("outstretched_arm", "动作姿态/手部动作", "伸出单臂"),
    ("arm_support", "动作姿态/头颈与倚靠", "手臂支撑"),
    ("head_tilt", "动作姿态/头颈与倚靠", "歪头"),
    ("head_on_shoulder", "动作姿态/头颈与倚靠", "头靠肩"),
    ("head_on_another's_shoulder", "动作姿态/头颈与倚靠", "头靠他人肩"),
    ("sitting_on_lap", "动作姿态/坐姿", "坐于膝上"),
    ("hug", "动作姿态/互动与双人", "拥抱"),
    ("headpat", "动作姿态/互动与双人", "摸头"),
    ("embrace", "动作姿态/互动与双人", "相拥"),
    ("nose_boop", "动作姿态/互动与双人", "碰鼻"),
    ("cowboy_shot", "构图镜头/取景范围", "七分身"),
    ("upper_body", "构图镜头/取景范围", "上半身"),
    ("full_body", "构图镜头/取景范围", "全身"),
    ("pov", "构图镜头/视角", "第一人称视角"),
    ("from_side", "构图镜头/视角", "侧面视角"),
    ("from_behind", "构图镜头/视角", "背后视角"),
    ("from_above", "构图镜头/视角", "俯视视角"),
    ("dutch_angle", "构图镜头/镜头语言", "倾斜镜头"),
    ("foreshortening", "构图镜头/构图", "透视缩短"),
    ("lips", "外貌特征/嘴部动作", "嘴唇"),
    ("teeth", "外貌特征/嘴部动作", "牙齿"),
    ("fangs", "外貌特征/嘴部动作", "虎牙"),
    ("upper_teeth_only", "外貌特征/嘴部动作", "只露上牙"),
    ("tongue_out", "外貌特征/嘴部动作", "吐舌"),
    ("spoken_heart", "场景环境/氛围粒子", "心头告白"),
    ("heart", "场景环境/氛围粒子", "爱心"),
    ("v-shaped_eyebrows", "外貌特征/表情", "V 形眉"),
    ("grin", "外貌特征/表情", "咧嘴笑"),
    ("smirk", "外貌特征/表情", "坏笑"),
    ("evil_smile", "外貌特征/表情", "邪笑"),
    ("sleeping", "外貌特征/情绪与状态", "熟睡"),
    # --- NSFW 第二批 (related_tag 池第一轮未策展部分) ---
    ("breasts_out", "服装/服装状态", "双乳外露"),
    ("gag", "动作姿态/束缚与调教", "塞口物"),
    ("shibari_over_clothes", "动作姿态/束缚与调教", "衣上绳缚"),
    ("futa_with_female", "动作姿态/性行为", "扶她×女"),
    ("tentacle_sex", "动作姿态/性行为", "触手性交"),
    ("object_insertion", "动作姿态/性行为", "异物插入"),
    ("cooperative_paizuri", "动作姿态/性行为", "双人乳交", {"h": 2}),
    ("handsfree_paizuri", "动作姿态/性行为", "无手乳交", {"h": 0}),
    ("perpendicular_paizuri", "动作姿态/性行为", "垂直乳交", {"h": 2}),
    ("deep_penetration", "动作姿态/性行为", "深插"),
    ("male_penetrated", "动作姿态/性行为", "男性被插入", {"g": "male"}),
    ("spread_pussy", "外貌特征/身体细节", "分开阴部", {"g": "female"}),
    ("butt_crack", "外貌特征/身体细节", "臀缝"),
]

# ---------------------------------------------------------------- 互斥域 (nsfw_grouprules.json)
# 与出厂 grouprules.json 同名 id 的域会按并集合并 (加载器扩展)。

def _domain_members():
    pos = ["missionary", "doggystyle", "cowgirl position", "reverse cowgirl position",
           "squatting cowgirl position", "prone bone", "upright straddle",
           "sex from behind", "standing sex", "girl on top", "boy on top",
           "folded", "m legs", "straddling", "sitting on person"]
    return {
        "nsfw.sex_position": pos,
        "nsfw.penetration": ["vaginal", "anal", "double penetration",
                             "vaginal object insertion", "anal object insertion"],
        "nsfw.cum_target": ["cum in pussy", "internal cumshot", "cum in mouth",
                            "cum in ass", "cum on body", "cum on breasts",
                            "cum on hair", "cum on feet", "cum on face", "facial",
                            "bukkake", "cum on clothes"],
        "nsfw.self_act": ["masturbation", "female masturbation", "male masturbation",
                          "futanari masturbation", "mutual masturbation"],
        "nsfw.toy_device": ["sex toy", "vibrator", "vibrator under clothes",
                            "remote control vibrator", "egg vibrator",
                            "hitachi magic wand", "dildo", "strap-on", "onahole"],
        # 与出厂域同名 → 并集 (口部资源账本: 一张嘴同时只能干一件事)
        "legacy.mouth": ["kissing", "deep kiss", "french kiss", "neck kiss",
                         "fellatio", "irrumatio", "deepthroat",
                         "cooperative fellatio", "cunnilingus", "licking penis",
                         "licking pussy", "breast sucking", "licking breasts",
                         "ball gag", "cloth gag", "tape gag", "improvised gag",
                         "wiffle gag", "gagged", "cum in mouth", "onahole"],
        "orientation": ["hetero", "yuri", "yaoi"],
    }

# ---------------------------------------------------------------- 跨池规则 (nsfw_conflicts.json)
# word↔slot 批量互斥; 槽位名用现行 "轴/槽位" 路径。

CROSS_RULES = [
    {"id": "ext.nipple-cover-vs-exposed",
     "note": "遮盖乳头 ↔ 乳晕/乳头外露 (danbooru 语义互斥)",
     "left": {"kind": "tags", "value": ["covered nipples", "covered chest"]},
     "right": [{"kind": "tag", "value": "areolae"},
               {"kind": "tag", "value": "erect nipples"},
               {"kind": "tag", "value": "puffy nipples"},
               {"kind": "tag", "value": "large areolae"}]},
    {"id": "ext.completely-nude-vs-clothes",
     "note": "全裸 ↔ 核心穿着 (腿袜/配饰不拦: 裸+袜是高频组合)",
     "left": {"kind": "tags", "value": ["completely nude", "full nudity"]},
     "right": [{"kind": "sub", "value": "服装/上装"},
               {"kind": "sub", "value": "服装/下装"},
               {"kind": "sub", "value": "服装/裙装与礼服"},
               {"kind": "sub", "value": "服装/职业与制服"},
               {"kind": "sub", "value": "服装/传统与民族"},
               {"kind": "sub", "value": "服装/特色与运动装"},
               {"kind": "sub", "value": "服装/腿袜与内衣"},
               {"kind": "sub", "value": "服装/鞋子"}]},
    {"id": "ext.topless-vs-top",
     "note": "露上身 ↔ 上装 (外套敞开不算)",
     "left": {"kind": "tags", "value": ["topless", "bare chest", "covered nipples",
                                        "hair over breasts", "breasts out"]},
     "right": [{"kind": "sub", "value": "服装/上装"}]},
    {"id": "ext.bottomless-vs-bottom",
     "note": "露下身 ↔ 下装",
     "left": {"kind": "tags", "value": ["bottomless"]},
     "right": [{"kind": "sub", "value": "服装/下装"}]},
    {"id": "ext.underwear-only-vs-clothes",
     "note": "只穿内衣 ↔ 主要外衣",
     "left": {"kind": "tags", "value": ["underwear only", "underwear", "lingerie",
                                        "bra", "panties"]},
     "right": [{"kind": "sub", "value": "服装/上装"},
               {"kind": "sub", "value": "服装/下装"},
               {"kind": "sub", "value": "服装/裙装与礼服"},
               {"kind": "sub", "value": "服装/职业与制服"},
               {"kind": "sub", "value": "服装/传统与民族"},
               {"kind": "sub", "value": "服装/特色与运动装"}]},
    {"id": "ext.bikini-top-only-vs-top",
     "note": "只穿比基尼上装 ↔ 上装",
     "left": {"kind": "tags", "value": ["bikini top only", "naked shirt"]},
     "right": [{"kind": "sub", "value": "服装/上装"}]},
    {"id": "ext.footjob-vs-shoes",
     "note": "足交 ↔ 鞋子",
     "left": {"kind": "tags", "value": ["footjob", "two-footed footjob",
                                        "footjob with legwear", "cum on feet"]},
     "right": [{"kind": "sub", "value": "服装/鞋子"}]},
    {"id": "ext.clothed-sex-vs-nude",
     "note": "着衣性交 ↔ 裸露类",
     "left": {"kind": "tags", "value": ["clothed sex"]},
     "right": [{"kind": "tag", "value": "nude"}, {"kind": "tag", "value": "completely nude"},
               {"kind": "tag", "value": "partially nude"}, {"kind": "tag", "value": "bottomless"}]},
    {"id": "ext.nohumans-vs-nsfw-action",
     "note": "no humans ↔ 性行为类槽位 (动作轴不在 no-humans 既有抑制范围)",
     "left": {"kind": "tag", "value": "no humans"},
     "right": [{"kind": "sub", "value": "动作姿态/体位"},
               {"kind": "sub", "value": "动作姿态/性行为"},
               {"kind": "sub", "value": "动作姿态/束缚与调教"},
               {"kind": "sub", "value": "动作姿态/高潮与体液"},
               {"kind": "sub", "value": "动作姿态/互动与双人"}]},
    {"id": "ext.animal-vs-sex",
     "note": "动物伙伴 ↔ 性行为/体位/高潮 (防止 dog + doggystyle 这类灾难共现)",
     "left": {"kind": "sub", "value": "道具武器/动物伙伴"},
     "right": [{"kind": "sub", "value": "动作姿态/性行为"},
               {"kind": "sub", "value": "动作姿态/体位"},
               {"kind": "sub", "value": "动作姿态/高潮与体液"},
               {"kind": "sub", "value": "动作姿态/束缚与调教"}]},
    {"id": "ext.bondage-vs-freewear",
     "note": "绳缚全身 ↔ 上装/下装 (局部束缚不拦)",
     "left": {"kind": "tags", "value": ["bound", "shibari", "suspension", "frogtie"]},
     "right": [{"kind": "sub", "value": "服装/上装"},
               {"kind": "sub", "value": "服装/下装"}]},
]
